# GNU Gettext library

GETTEXT_VERSION=0.19.3
GETTEXT_ARCHIVE=gettext-$GETTEXT_VERSION.tar.xz
GETTEXT_URL=http://ftp.gnu.org/pub/gnu/gettext/$GETTEXT_ARCHIVE
gettext_DEPENDENCIES="gnulib gperf pkgconfig"

function gettext_init {
    echo "0"
}

function gettext_fetch {
    arch_fetch $1 $GETTEXT_URL $GETTEXT_ARCHIVE
}

function gettext_extract {
    arch_extract $1 $GETTEXT_ARCHIVE
}

function gettext_build {
    local ADDENDUM=""
    if [ $USE_TOOLCHAIN -gt 0 ]; then
	$ADDENDUM="CC=$CC CXX=$CXX CPP=$CPP CFLAGS=\"$CFLAGS\" CPPFLAGS=\"$CPPFLAGS\" CXXFLAGS=\"$CXXFLAGS\" LD=$LD LDFLAGS=\"$LDFLAGS\" "
    fi
    cd $WORK_ROOT/build/$1
    if [ $TRACE_RUN -eq 0 ]; then
	GNULIB_SRCDIR=${WORK_ROOT}/build/gnulib ./autogen.sh &> ${WORK_ROOT}/logs/$1-autoconf.log
	./configure --prefix=$INSTALL_PREFIX --sysconfdir=/etc --localstatedir=/var --enable-dependency-tracking $ADDENDUM 2>&1 > ${WORK_ROOT}/logs/$1-configure.log
	make -j${JOBS} &> ${WORK_ROOT}/logs/$1.log && make install clean &>/dev/null
    fi
    DEP_BUILT="$1 $DEP_BUILT"
}

function gettext_actual {
    # TODO: implement a version check! Stub for now
    echo "2"
}

function gettext_getactualdependency {
    echo $gettext_DEPENDENCIES
}

