# GNU Guile

guile_DEPENDENCIES="libffi libatomic_ops gnulib bdwgc libunistring gettext"

function guile_init {
    echo "0"
}

function guile_fetch {
    git_fetch $1 http://git.sv.gnu.org/r/guile.git
}

function guile_extract {
    git_extract $1
}

function guile_build {
    local ADDENDUM=""
    if [ $USE_TOOLCHAIN -gt 0 ]; then
	$ADDENDUM="CC=$CC CXX=$CXX CPP=$CPP CFLAGS=\"$CFLAGS\" CPPFLAGS=\"$CPPFLAGS\" CXXFLAGS=\"$CXXFLAGS\" LD=$LD LDFLAGS=\"$LDFLAGS\" "
    fi
    cd $WORK_ROOT/build/$1
    if [ $TRACE_RUN -eq 0 ]; then
	GNULIB_SRCDIR=${WORK_ROOT}/build/gnulib ./autogen.sh &> ${WORK_ROOT}/logs/$1-autoconf.log
	./configure --prefix=$INSTALL_PREFIX --sysconfdir=/etc --localstatedir=/var --enable-dependency-tracking $ADDENDUM > ${WORK_ROOT}/logs/$1-configure.log
	make -j${JOBS} &> ${WORK_ROOT}/logs/$1.log && make -j${JOBS} install clean &> /dev/null
    fi
    DEP_BUILT="$1 $DEP_BUILT"
}

function guile_actual {
	echo "2"
}

function guile_getactualdependency {
    echo $guile_DEPENDENCIES
}

