# libatomic ops - was removed from GCC source tree

libatomic_ops_DEPENDENCIES=""

function libatomic_ops_init {
    echo "0"
}

function libatomic_ops_fetch {
    git_fetch $1 https://github.com/ivmai/libatomic_ops.git
}

function libatomic_ops_extract {
    git_extract $1
}

function libatomic_ops_build {
    local ADDENDUM=""
    if [ $USE_TOOLCHAIN -gt 0 ]; then
	$ADDENDUM="CC=$CC CXX=$CXX CPP=$CPP CFLAGS=\"$CFLAGS\" CPPFLAGS=\"$CPPFLAGS\" CXXFLAGS=\"$CXXFLAGS\" LD=$LD LDFLAGS=\"$LDFLAGS\" "
    fi
    cd $WORK_ROOT/build/$1
    if [ $TRACE_RUN -eq 0 ]; then
	./autogen.sh  &> ${WORK_ROOT}/logs/$1-autoconf.log
	./configure --prefix=$INSTALL_PREFIX --sysconfdir=/etc --localstatedir=/var --enable-dependency-tracking $ADDENDUM > ${WORK_ROOT}/logs/$1-configure.log
	make -j${JOBS} &> ${WORK_ROOT}/logs/$1.log && make install clean &> /dev/null
    fi
    DEP_BUILT="$1 $DEP_BUILT"
}

function libatomic_ops_actual {
	echo "2"
}

function libatomic_ops_getactualdependency {
    echo $libatomic_ops_DEPENDENCIES
}

