
# libevent

LIBEVENT_VERSION=2.0.21
LIBEVENT_ARCHIVE=libevent-$LIBEVENT_VERSION-stable.tar.gz
LIBEVENT_URL=https://github.com/downloads/libevent/libevent/$LIBEVENT_ARCHIVE


libevent_DEPENDENCIES=toolchain

function libevent_init {
    echo "0"
}

function libevent_fetch {
    arch_fetch $1 $LIBEVENT_URL $LIBEVENT_ARCHIVE
}

function libevent_extract {
    arch_extract $1 $LIBEVENT_ARCHIVE
}

function libevent_build {
    local ADDENDUM=""
    if [ $USE_TOOLCHAIN -gt 0 ]; then
	$ADDENDUM="CC=$CC CXX=$CXX CPP=$CPP CFLAGS=\"$CFLAGS\" CPPFLAGS=\"$CPPFLAGS\" CXXFLAGS=\"$CXXFLAGS\" LD=$LD LDFLAGS=\"$LDFLAGS\" "
    fi
    cd $WORK_ROOT/build/$1
    if [ $TRACE_RUN -eq 0 ]; then
	./configure --prefix=$INSTALL_PREFIX --with-pic --enable-dependency-tracking $ADDENDUM > ${WORK_ROOT}/logs/$1-configure.log
	make -j4 &> ${WORK_ROOT}/logs/$1.log  && make install clean &> /dev/null
    fi
    DEP_BUILT="$1 $DEP_BUILT"
}

function libevent_actual {
    # TODO: implement a version check! Stub for now
    echo "2"
}

function libevent_getactualdependency {
    echo ""
}

