# libnatpmp

LIBNATPMP_VERSION=20140401
LIBNATPMP_ARCHIVE=libnatpmp-$LIBNATPMP_VERSION.tar.gz
LIBNATPMP_URL=http://miniupnp.free.fr/files/download.php?file=$LIBNATPMP_ARCHIVE

libnatpmp_DEPENDENCIES="toolchain"

function libnatpmp_init {
    echo "0"
}

function libnatpmp_fetch {
    arch_fetch $1 $LIBNATPMP_URL $LIBNATPMP_ARCHIVE
}

function libnatpmp_extract {
    arch_extract $1 $LIBNATPMP_ARCHIVE
}

function libnatpmp_build {
    cd $WORK_ROOT/build/$1
    local TK=" "
    if [ $USE_TOOLCHAIN -gt 0 ]; then
	TK="CC=\"$CC $CFLAGS\" "
    fi
    if [ $TRACE_RUN -eq 0 ]; then
	make $TK INSTALLPREFIX=${INSTALL_PREFIX} &> ${WORK_ROOT}/logs/$1.log
	make install &> /dev/null
	cp ${WORK_ROOT}/build/libnatpmp/declspec.h ${INSTALL_PREFIX}/include
    fi
    DEP_BUILT="$1 $DEP_BUILT"
}

function libnatpmp_actual {
    # TODO: implement a version check! Stub for now
    echo "2"
}

function libnatpmp_getactualdependency {
    echo $libnatpmp_DEPENDENCIES
}

