libusb_DEPENDENCIES=toolchain

function libusb_init {
    echo "0"
}

function libusb_fetch {
    git_fetch $1 http://git.libusb.org/libusb.git
}

function libusb_extract {
    git_extract $1
}

function libusb_build {
    local ADDENDUM=""
    if [ $USE_TOOLCHAIN -gt 0 ]; then
	$ADDENDUM="CC=$CC CXX=$CXX CPP=$CPP CFLAGS=\"$CFLAGS\" CPPFLAGS=\"$CPPFLAGS\" CXXFLAGS=\"$CXXFLAGS\" LD=$LD LDFLAGS=\"$LDFLAGS\" "
    fi
    cd $WORK_ROOT/build/$1
    if [ $TRACE_RUN -eq 0 ]; then
	./autogen.sh &> ${WORK_ROOT}/logs/$1-autoconf.log
	./configure --prefix=$INSTALL_PREFIX --sysconfdir=/etc --localstatedir=/var --with-pic=all --enable-dependency-tracking --enable-debug-log $ADDENDUM > ${WORK_ROOT}/logs/$1-configure.log
	make &> ${WORK_ROOT}/logs/$1 && make install clean &> /dev/null
    fi
    DEP_BUILT="$1 $DEP_BUILT"
}

function libusb_actual {
    # TODO: implement a version check! Stub for now
    echo "2"
}

function libusb_getactualdependency {
    echo $libusb_DEPENDENCIES
}

