# GNU libunistring

libunistring_DEPENDENCIES="gnulib"

function libunistring_init {
    echo "0"
}

function libunistring_fetch {
    git_fetch $1 git://git.savannah.gnu.org/libunistring.git
}

function libunistring_extract {
    git_extract $1
}

function libunistring_build {
    local ADDENDUM=""
    if [ $USE_TOOLCHAIN -gt 0 ]; then
	$ADDENDUM="CC=$CC CXX=$CXX CPP=$CPP CFLAGS=\"$CFLAGS\" CPPFLAGS=\"$CPPFLAGS\" CXXFLAGS=\"$CXXFLAGS\" LD=$LD LDFLAGS=\"$LDFLAGS\" "
    fi
    cd $WORK_ROOT/build/$1
    if [ $TRACE_RUN -eq 0 ]; then
	GNULIB_TOOL="${WORK_ROOT}/build/gnulib/gnulib-tool " PREFIX=$INSTALL_PREFIX ./autogen.sh &> ${WORK_ROOT}/logs/$1-autoconf.log
	./configure --prefix=$INSTALL_PREFIX --sysconfdir=/etc --localstatedir=/var --enable-dependency-tracking --enable-threads=posix $ADDENDUM > ${WORK_ROOT}/logs/$1-configure.log
	make -j${JOBS} &> ${WORK_ROOT}/logs/$1.log && make install clean &> /dev/null
    fi
    DEP_BUILT="$1 $DEP_BUILT"
}

function libunistring_actual {
	echo "2"
}

function libunistring_getactualdependency {
    echo $libunistring_DEPENDENCIES
}

