# OpenCT

openct_DEPENDENCIES="toolchain libusb_compat"

function openct_init {
    service openct stop
    echo "0"
}

function openct_fetch {
    git_fetch $1 https://github.com/OpenSC/openct.git
}

function openct_extract {
    git_extract $1
}

function openct_build {
    local ADDENDUM=""
    if [ $USE_TOOLCHAIN -gt 0 ]; then
	$ADDENDUM="CC=$CC CXX=$CXX CPP=$CPP CFLAGS=\"$CFLAGS\" CPPFLAGS=\"$CPPFLAGS\" CXXFLAGS=\"$CXXFLAGS\" LD=$LD LDFLAGS=\"$LDFLAGS\" "
    fi
    cd $WORK_ROOT/build/$1
    ./bootstrap
    ./configure --prefix=$INSTALL_PREFIX --enable-dependency-tracking --enable-usb --enable-non-privileged --with-pic=all --sysconfdir=/etc --localstatedir=/var $ADDENDUM
    make -j4 && make install
    cp etc/init-script /etc/init.d/openct
    ln -s /etc/init.d/openct /etc/rc0.d/K50openct
    ln -s /etc/init.d/openct /etc/rc1.d/S50openct
    ln -s /etc/init.d/openct /etc/rc2.d/S50openct
    ln -s /etc/init.d/openct /etc/rc3.d/S50openct
    ln -s /etc/init.d/openct /etc/rc4.d/S50openct
    ln -s /etc/init.d/openct /etc/rc5.d/S50openct
    ln -s /etc/init.d/openct /etc/rc6.d/K20openct

    cp etc/openct.udev /etc/udev/rules.d/95-openct.rules
    cp etc/openct_usb /lib/udev/openct_usb
    cp etc/openct_pcmcia /lib/udev/openct_pcmcia
    cp etc/openct_serial /lib/udev/openct_serial
    chmod +x /etc/init.d/openct
    update-rc.d openct defaults
    G_VALID=`getent group usb | wc -l`
    if [ $G_VALID -lt 1 ]; then
	groupadd -r usb
    fi
    G_VALID=`getent group openctd | wc -l`
    if [ $G_VALID -lt 1 ]; then
	useradd -m -U -r openctd
    fi
    service openct start

    DEP_BUILT="$1 $DEP_BUILT"
}

function openct_actual {
    # TODO: implement a version check! Stub for now
    echo "2"
}

function openct_getactualdependency {
    echo $openct_DEPENDENCIES
}

