# pkg-config manager


pkgconfig_DEPENDENCIES="gnulib"

function pkgconfig_init {
    echo "0"
}

function pkgconfig_fetch {
    git_fetch $1 http://anongit.freedesktop.org/git/pkg-config.git
}

function pkgconfig_extract {
    git_extract $1
}

function pkgconfig_build {
    local ADDENDUM=""
    if [ $USE_TOOLCHAIN -gt 0 ]; then
	$ADDENDUM="CC=$CC CXX=$CXX CPP=$CPP CFLAGS=\"$CFLAGS\" CPPFLAGS=\"$CPPFLAGS\" CXXFLAGS=\"$CXXFLAGS\" LD=$LD LDFLAGS=\"$LDFLAGS\" "
    fi
    cd $WORK_ROOT/build/$1
    if [ $TRACE_RUN -eq 0 ]; then
	GNULIB_SRCDIR=${WORK_ROOT}/build/gnulib ./autogen.sh --prefix=$INSTALL_PREFIX --sysconfdir=/etc --localstatedir=/var --enable-dependency-tracking --with-internal-glib $ADDENDUM > ${WORK_ROOT}/logs/$1-configure.log
	make -j${JOBS} &> ${WORK_ROOT}/logs/$1.log && make install clean &> /dev/null
    fi
    DEP_BUILT="$1 $DEP_BUILT"
}

function pkgconfig_actual {
	echo "2"
}

function pkgconfig_getactualdependency {
    echo $pkgconfig_DEPENDENCIES
}

