# GNU makeinfo/TeXinfo

TEXINFO_VERSION=5.2
TEXINFO_ARCHIVE=texinfo-$TEXINFO_VERSION.tar.gz
TEXINFO_URL=http://ftp.gnu.org/gnu/texinfo/$TEXINFO_ARCHIVE

texinfo_DEPENDENCIES=ncurses


function texinfo_init {
    echo "0"
}

function texinfo_fetch {
    arch_fetch $1 $TEXINFO_URL $TEXINFO_ARCHIVE
}

function texinfo_extract {
    arch_extract $1 $TEXINFO_ARCHIVE
}

function texinfo_build {
    local ADDENDUM=""
    if [ $USE_TOOLCHAIN -gt 0 ]; then
	$ADDENDUM="CC=$CC CXX=$CXX CPP=$CPP CFLAGS=\"$CFLAGS\" CPPFLAGS=\"$CPPFLAGS\" CXXFLAGS=\"$CXXFLAGS\" LD=$LD LDFLAGS=\"$LDFLAGS\" "
    fi
    cd $WORK_ROOT/build/$1
    if [ $TRACE_RUN -eq 0 ]; then
	./configure --prefix=$INSTALL_PREFIX --sysconfdir=/etc --localstatedir=/var --enable-threads=posix --enable-dependency-tracking $ADDENDUM > ${WORK_ROOT}/logs/$1-configure.log
	make -j${JOBS} &> ${WORK_ROOT}/logs/$1.log && make install clean &> /dev/null
    fi
    DEP_BUILT="$1 $DEP_BUILT"
}

function texinfo_actual {
    echo "2"
}

function texinfo_getactualdependency {
    echo $texinfo_DEPENDENCIES
}

