
# TeX Live

TEXLIVE_YEAR=2014
TEXLIVE_VERSION=${TEXLIVE_YEAR}0525
TEXLIVE_SOURCE_ARCHIVE=texlive-$TEXLIVE_VERSION-source.tar.xz
TEXLIVE_MF_ARCHIVE=texlive-$TEXLIVE_VERSION-texmf.tar.xz
TEXLIVE_SOURCE_URL=ftp://tug.org/historic/systems/texlive/$TEXLIVE_YEAR/$TEXLIVE_SOURCE_ARCHIVE
TEXLIVE_MF_URL=ftp://tug.org/historic/systems/texlive/$TEXLIVE_YEAR/$TEXLIVE_MF_ARCHIVE

texlive_DEPENDENCIES="ncurses texinfo zlib"
# lua X


function texlive_init {
    echo "0"
}

function texlive_fetch {
    arch_fetch $1 $TEXLIVE_SOURCE_URL $TEXLIVE_SOURCE_ARCHIVE
    arch_fetch $1 $TEXLIVE_MF_URL $TEXLIVE_MF_ARCHIVE
}

function texlive_extract {
    arch_extract $1 $TEXLIVE_SOURCE_ARCHIVE
    if [ -d $INSTALL_PREFIX/share/texmf ]; then
	if [ ! -e /texmf ]; then
	    ln -s $INSTALL_PREFIX/share/texmf /texmf
	fi
    else
	arch_extract $1 $TEXLIVE_MF_ARCHIVE $INSTALL_PREFIX/share/texmf
	ln -s $INSTALL_PREFIX/share/texmf /texmf
    fi
}

function texlive_build {
    local ADDENDUM=""
    if [ $USE_TOOLCHAIN -gt 0 ]; then
	$ADDENDUM="CC=$CC CXX=$CXX CPP=$CPP CFLAGS=\"$CFLAGS\" CPPFLAGS=\"$CPPFLAGS\" CXXFLAGS=\"$CXXFLAGS\" LD=$LD LDFLAGS=\"$LDFLAGS\" "
    fi
    cd $WORK_ROOT/build/$1
    if [ $TRACE_RUN -eq 0 ]; then
	mkdir build
	cd build
	../configure --prefix=$INSTALL_PREFIX --sysconfdir=/etc --localstatedir=/var --enable-dependency-tracking --with-system-zlib --without-x --disable-native-texlive-build $ADDENDUM > ${WORK_ROOT}/logs/$1-configure.log
	make -j${JOBS} &> ${WORK_ROOT}/logs/$1.log && make install clean &> /dev/null
    fi
    DEP_BUILT="$1 $DEP_BUILT"
}

function texlive_actual {
    echo "2"
}

function texlive_getactualdependency {
    echo $texlive_DEPENDENCIES
}

