
# Zlib compression library

ZLIB_VERSION=1.2.8
ZLIB_ARCHIVE=zlib-$ZLIB_VERSION.tar.gz
ZLIB_URL=http://zlib.net/$ZLIB_ARCHIVE
ZTK=" "

zlib_DEPENDENCIES="toolchain"

function zlib_init {
    ARCH_TEST=`uname -p | grep -c x86_64`
    if [ $ARCH_TEST -gt 0 ]; then
	ZTK=" --64 "
    fi
    if [ $USE_TOOLCHAIN -lt 1 ]; then
	echo "0"
    else
	echo "1"
    fi
}

function zlib_fetch {
    arch_fetch $1 $ZLIB_URL $ZLIB_ARCHIVE
}

function zlib_extract {
    arch_extract $1 $ZLIB_ARCHIVE
}

function zlib_build {
    local ADDENDUM=""
    if [ $USE_TOOLCHAIN -gt 0 ]; then
	export CC="/usr/bin/gcc-trunk $CFLAGS "
    fi
    cd $WORK_ROOT/build/$1
    if [ $TRACE_RUN -eq 0 ]; then
	./configure --prefix=$INSTALL_PREFIX --sysconfdir=/etc --localstatedir=/var $ZTK > ${WORK_ROOT}/logs/$1-configure.log
	make &> ${WORK_ROOT}/logs/$1.log && make install clean &> /dev/null
    fi
    if [ $USE_TOOLCHAIN -gt 0 ]; then
	unset CC
    fi
    DEP_BUILT="$1 $DEP_BUILT"
}

function zlib_actual {
    # TODO: implement a version check! Stub for now
    echo "2"
}

function zlib_getactualdependency {
    echo $zlib_DEPENDENCIES
}

